DROP TABLE IF EXISTS BOOKING;

CREATE TABLE BOOKING(
  BOOKING_ID INT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID INT NOT NULL,
  CUSTOMER_ID INT NOT NULL,
  BREAKFAST VARCHAR(150) NULL,
  START_DATE DATE NULL,
  END_DATE DATE NULL,
  TOTAL_CHARGE DECIMAL NULL
);


DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER(
   CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY;
   CUSTOMER_NAME VARCHAR(150) NOT NULL
);

DROP TABLE IF EXISTS ROOM;

CREATE TABLE ROOM(
   ROOM_ID INT AUTO_INCREMENT PRIMARY KEY,
   ROOM_TYPE VARCHAR(150) NOT NULL,
   ROOM_PRICE DECIMAL NOT NULL,
   STATUS VARCHAR(150) NULL,
   BOOKING_ID INT NULL
);
